/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * balances.java
 *
 * Created on Sep 8, 2009, 7:11:00 PM
 */

package estadosfinancieros;

import java.text.DateFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.Set;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Query;
import org.jdesktop.beansbinding.Converter;

/**
 *
 * @author sxceron
 */
public class balances extends javax.swing.JFrame {

    private Empresa empresa;
    private String bal;
    /** Creates new form balances */
    public balances() {
        
    }

    public void init(){
        initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        finanzasPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("finanzasPU").createEntityManager();
        balanceQuery = java.beans.Beans.isDesignTime() ? null : finanzasPUEntityManager.createQuery("SELECT b FROM Balance b");
        balanceList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : balanceQuery.getResultList();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(null);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(estadosfinancieros.EstadosFinancierosApp.class).getContext().getResourceMap(balances.class);
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 140, 142, 16);

        jComboBox1.setName("jComboBox1"); // NOI18N

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${empresa.balances}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jComboBox1);
        jComboBoxBinding.setConverter(new BalanceConverter());
        bindingGroup.addBinding(jComboBoxBinding);
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${bal}"), jComboBox1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(240, 160, 250, 27);

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 190, 134, 29);

        jButton2.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 190, 106, 29);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(estadosfinancieros.EstadosFinancierosApp.class).getContext().getActionMap(balances.class, this);
        jButton3.setAction(actionMap.get("quit")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        getContentPane().add(jButton3);
        jButton3.setBounds(700, 360, 75, 29);

        jLabel2.setIcon(resourceMap.getIcon("jLabel2.icon")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 810, 410);

        bindingGroup.bind();

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-810)/2, (screenSize.height-410)/2, 810, 410);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*String ne = JOptionPane.showInputDialog("Nombre de la empresa:");*/
        empresa = finanzasPUEntityManager.merge(empresa);
        Balance b = new Balance();
        b.setEmpresa(empresa);
        b.setFecha(new Date());
        finanzasPUEntityManager.getTransaction().begin();
        finanzasPUEntityManager.persist(b);
        empresa.getBalances().add(b);
        finanzasPUEntityManager.persist(empresa);
        finanzasPUEntityManager.getTransaction().commit();

        EsquemaMayorMain esq = new EsquemaMayorMain();
        esq.setBalance(b);
        esq.init();
        esq.setVisible(true);

        this.setVisible(false);
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Query q = finanzasPUEntityManager.createQuery("select b from Balance b where b.fecha=:fecha");
            q.setParameter("fecha", DateFormat.getDateInstance().parse(bal));
            Balance b = (Balance) q.getResultList().get(0);
            System.out.println(b);
            if (b != null) {
                EsquemaMayorMain esq = new EsquemaMayorMain();
                esq.setBalance(b);
                esq.init();
                esq.setVisible(true);
                this.setVisible(false);
            }
        } catch (ParseException ex) {
            Logger.getLogger(balances.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                balances b = new balances();
                b.init();
                b.setVisible(true);
            }
        });
    }

    public Empresa getEmpresa() {
        return empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    public String getBal() {
        return bal;
    }

    public void setBal(String bal) {
        this.bal = bal;
    }

    class BalanceConverter extends Converter {
        @Override
        public Object convertForward(Object arg) {
            Vector<String>  v = new Vector<String>();
            for( Object a : ((Set<Balance>)arg) ){
                System.out.println(a);
                Date fecha = ((Balance)a).getFecha();
                String f = DateFormat.getDateInstance().format(fecha);

                v.add(f);
            }

            return v;
        }

        @Override
        public Object convertReverse(Object arg) {
            return arg;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<estadosfinancieros.Balance> balanceList;
    private javax.persistence.Query balanceQuery;
    private javax.persistence.EntityManager finanzasPUEntityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
