/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Inicio.java
 *
 * Created on Sep 7, 2009, 6:16:44 PM
 */
package estadosfinancieros;

import java.util.Vector;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.jdesktop.beansbinding.Converter;
import org.jvnet.substance.skin.SubstanceSaharaLookAndFeel;

/**
 *
 * @author sxceron
 */
public class Inicio extends javax.swing.JFrame {

    private Object selectedEmpresa;
    /** Creates new form Inicio */
    public Inicio() {
        
        try {
              UIManager.setLookAndFeel(new SubstanceSaharaLookAndFeel());
         // set UI manager properties here that affect Quaqua

         } catch (Exception e) {
             e.printStackTrace();
         }
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        finanzasPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("finanzasPU").createEntityManager();
        empresaQuery = java.beans.Beans.isDesignTime() ? null : finanzasPUEntityManager.createQuery("SELECT e FROM Empresa e");
        empresaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : empresaQuery.getResultList();
        balanceQuery = java.beans.Beans.isDesignTime() ? null : finanzasPUEntityManager.createQuery("SELECT b FROM Balance b");
        balanceList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : balanceQuery.getResultList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(null);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(estadosfinancieros.EstadosFinancierosApp.class).getContext().getResourceMap(Inicio.class);
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 190, 140, 29);

        jButton2.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 190, 111, 29);

        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 140, 154, 16);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(estadosfinancieros.EstadosFinancierosApp.class).getContext().getActionMap(Inicio.class, this);
        jButton3.setAction(actionMap.get("quit")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        getContentPane().add(jButton3);
        jButton3.setBounds(700, 360, 75, 29);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setName("jComboBox1"); // NOI18N

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, empresaQuery, eLProperty, jComboBox1);
        jComboBoxBinding.setConverter(new EmpresaConverter());
        bindingGroup.addBinding(jComboBoxBinding);
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${selectedEmpresa}"), jComboBox1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(240, 160, 250, 27);

        jLabel2.setIcon(resourceMap.getIcon("jLabel2.icon")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 810, 410);

        bindingGroup.bind();

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-809)/2, (screenSize.height-405)/2, 809, 405);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Query q  = finanzasPUEntityManager.createQuery("select e from Empresa e where e.nombre=:nombre");
        q.setParameter("nombre", selectedEmpresa);
        Empresa e = (Empresa) q.getSingleResult();
        if( e != null ){
            System.out.println(e.getBalances().size());
            balances b = new balances();
            b.setEmpresa(e);
            b.init();
            b.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ne = JOptionPane.showInputDialog("Nombre de la empresa:");
        Empresa em = new Empresa();
        em.setNombre(ne);
        finanzasPUEntityManager.getTransaction().begin();
        finanzasPUEntityManager.persist(em);
        finanzasPUEntityManager.getTransaction().commit();
        balances b = new balances();
        b.setEmpresa(em);
        b.init();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    public Object getSelectedEmpresa() {
        return selectedEmpresa;
    }

    public void setSelectedEmpresa(Object selectedEmpresa) {
        this.selectedEmpresa = selectedEmpresa;
    }

    class EmpresaConverter extends Converter {
        Vector<Object> empresas = new Vector<Object>();
        @Override
        public Object convertForward(Object arg) {
            Vector<String>  v = new Vector<String>();
            for( Object a : ((Vector)arg) )
                v.add(((Empresa)a).getNombre());

            empresas = (Vector)arg;
            return v;
        }

        @Override
        public Object convertReverse(Object arg) {
            return empresas;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<estadosfinancieros.Balance> balanceList;
    private javax.persistence.Query balanceQuery;
    private java.util.List<estadosfinancieros.Empresa> empresaList;
    private javax.persistence.Query empresaQuery;
    private javax.persistence.EntityManager finanzasPUEntityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
