/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OrigenyResultado.java
 *
 * Created on Nov 29, 2009, 10:29:13 AM
 */

package estadosfinancieros;

/**
 *
 * @author sxceron
 */
public class OrigenyResultado extends javax.swing.JFrame {

    /** Creates new form OrigenyResultado */
    public OrigenyResultado() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panel = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(estadosfinancieros.EstadosFinancierosApp.class).getContext().getResourceMap(OrigenyResultado.class);
        panel.setContentType(resourceMap.getString("panel.contentType")); // NOI18N
        panel.setFont(resourceMap.getFont("panel.font")); // NOI18N
        panel.setText(resourceMap.getString("panel.text")); // NOI18N
        panel.setName("panel"); // NOI18N
        jScrollPane1.setViewportView(panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrigenyResultado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextPane panel;
    // End of variables declaration//GEN-END:variables

}
